---
abstract: 'Save instantiation arguments for later use.'
author:
  - 'Aran Deltac <bluefeet@gmail.com>'
build_requires:
  Test::Stream: '1.302026'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.042, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-BuildArgs
requires:
  Carp: '0'
  Moo: '2'
  Scalar::Util: '0'
  namespace::clean: '0.24'
  strictures: '2'
resources:
  bugtracker: https://github.com/bluefeet/MooX-BuildArgs/issues
  repository: git://github.com/bluefeet/MooX-BuildArgs.git
version: '0.02'
